---
layout: post
title:  写于三末
date:   2017-12-31 21:34:00
img: 
description: 前途犹在，其乐无穷。
---

之前觉悟到会听跟会说完全是两码事。那么，对于学术上的东西，尤其是思想，若要跟老外熟练交流，也必须加紧练习“说”。应该把每篇阅读过的论文或网页上的知识点整理起来做成PPT，然后练习做英文口头报告，这应该是能速成的方式。此外，不仅可以掌握生词，还能帮助理清逻辑。

随着文献阅读的深入，正如两个获得数学新视野奖的学霸所言，我发现数学真的是用来描述真实事件的，这才是它最美、最吸引人的地方。之前有过很多的思想都得不到确凿的说里求证，而数学，能让自己心里得个落实，甚至演变出更美妙的描绘和推论。从小到大，数学似乎是最拿不到“实用”中去、最理论的学科。虽然做过很多应用题，但哪怕是搞学术的我，也很少用到数学。其实我们一直没有体会到一点，那就是各种数学转换对解决实际问题的美，那是一种非常成功的满足感。以后给孩子们带数学的路，一定要让他们看到这种妙处的实用性。目前觉得，可以从统计模型带入门。

放下即人生。做人需要成功自不必说了，不是因为一定要好强斗狠，而是因为资源的有限性，不进则退，沦为别人的剥削品。所谓剥削品，也就是说自己的无为会比好强斗狠活得更辛苦，因为有一部分劳动成果被他人无尝占有了。当然也有人选择独善其身，甘于清贫。但盛世贫贱，圣人犹且耻之。即便自己能承受，难道都不用替自己的家人考虑？所以做人必须要成功，必须追求卓越。
那么何为成功？其实正常人类的智力体力等差别不大。也许有极个别精英有好的基因和成长环境，但我们追求成功，首先是要战胜大多数人，至少，要比昨天的自己更为卓越。这就叫成功。那么，既然正常人类的基本属性差不多，我们唯一能比人家胜出的，就是比别人花更多的时间。一碰就会的事情不算本事，常说天才的养成需要两万小时，那么成功的关键就在于如何捕获这两万小时。
一直认为做人成功的关键在于决心和恒心，但我时至今日才意识到，这其中的真谛在于“放下”。为什么我们经常觉得“没有时间”、“条件不成熟”、“不愿意”去做一些我们认为对的事情呢？其实不是因为我们缺乏决心和恒心，而是因为我们把这两种“心”禁锢在了其他的事情上。也就是说，我相信其实每个人都是有决心和恒心的，只不过被个别事件牵绊，“放不下”。只要果断放下折磨自己的事，勇敢地去做自己想做的事，总会发现决心和恒心。

在阳光海岸的努萨，看了密集压人的南半球的星空；第一次钓鱼，拉上了4条，不过一条是别人放的竿，还有一条快钓出水的时候脱钩了，真正完全自己钓到的是两条，都是金黄色的。放跑的那条是尖嘴黑条纹的。但鱼的嘴都很尖，把鱼钩整个吞进去，都拿不出来。

边吃零食边学习，防止变瘦或犯困。如果真的吸收不好，那就不停地吃，又不是完全不吸收。

一代战神、无双国士，韩信，他的死因应该是生活不能自理。也许他出生贵族养尊处优惯了（其实他衣锦还乡后报恩多人，却并没有对家族前辈有所纪念，个中也值得玩味），但从他乞食为生开始，就注定了最后的悲剧。第一，乞讨说明他有依赖性，不敢自己称王，只想替人卖命；第二，说明他喜欢打仗的同时不可能有胸怀天下黎民百姓的情操，若能忌讳祸害苍生的兵事，也许他就不会攻齐，尽量止战，而且如果他有安天下的胸怀，那么天下安定后他会选择功成身退，待需要时再出山；第三，由于他无法自食其力，因此在被“软禁”京城时仍不敢选择独自归隐，不愿回到那不堪回首的乞讨生涯中去。其实在某些人情世故方面，他与项羽还是有点像的，善良、傲慢、幼稚。可惜了一代战神。

房子和银行一样是存钱罐。银行里的钱是用来消费的，房子里的钱是用来买房的。……

今天起，早上不带白开水了，开始带茶水。

有些人想晒黑，可能是想匀称些。现在我的脸和脖子以及前臂感觉白不回来了。何况脖子前后和前臂内外侧都不均匀，看着像没洗干净……

之前突然暴瘦以及时不时的肠胃不适，可能是因为牛奶喝多了。

之前觉得咖啡作为粉末一饮而尽，茶叶要泡上好几道，所以可能每天喝咖啡摄入咖啡因更多，更不用说其他糖类等成分的差异。现在喝茶日常化了以后又发现，一水杯的茶可以喝一天，但泡一杯咖啡可能很快就喝完，按照这种喝法，那么咖啡因的瞬时摄入量也是不同的。这不仅是因为冲泡的方式不同，也可能是因为咖啡诱人，让人停不下来，而茶叶怡人，不会令人停不下来。

提前好几天发了补助（比上次提前了7天），哎呀，真是人逢喜事肚子饿啊，突然胃就叫了。赶在冬至前一天发下来，也是蛮有中国特色的。

婴儿好动，老人喜静。现代社会人普遍显得年轻，可能是诱惑太多应接不暇，让人始终像孩童一般充满新鲜感。

面粉的价格居然只有米的一半，唉呀早说嘛。突然意识到蒸饺比汤饺好的地方就是没包紧也不至于馅流出来。难得过上一个白昼最长的冬至，一定要包饺子纪念一下。也纪念一下已故的亲人，小时候这会儿应该很热闹了吧。第三次徒步去图旺，终于走对了既定路线，在重要的转弯口，居然看到一棵依然盛开着的蓝花楹。满城皆落，还以为再也看不到这美景了。

面食先腻嘴巴，米饭先觉肚饱，究竟哪个更扛饿，哪个更易吸收？有人说虽然面食更易消化，但煮熟的米饭含水量比面食高很多，所以如果吃一样的量，那么面食会更扛饿。我觉得含水量高可能也是米饭不会腻口的主要原因吧。如果面食真的更容易消化吸收、更容易扛饿，那么正好解决了我目前遇到的两大问题。而且这里的面粉单价只有大米的一半，后面测试一下食量上是否有两倍，但感觉是没有的，就算平时吃再多米饭都觉得饿，但人体也不可能一下子摄入两倍的淀粉量吧。另外，我买的是最便宜的长米，感觉饭粒中心很稀，也没有香气，估计营养成分不高。

蒸完馒头，水基本上没有少。时间跟烧米饭差不多，也就是说烧米饭加的一倍多的水基本上全被米吸收了。而和面加的水大约只有面粉的一半。也就是含水量差别是两三倍。

人只要对一件事情感兴趣，积极性就会调动起来，就会顺带着在做其他事情的时候都很有积极性。所以有理想有兴趣真的可以塑造一个完全不同的人。

酵母在有氧呼吸的时候面团内氧气和二氧化碳的体积抵消，气压不会发生多大变化。面团经揉捏后内部的空气已经基本上被挤光了，所以静置下来后应该过不了多久酵母就会进入无氧呼吸。所以一开始要使酵母快速增殖，那么最好用温度水把面粉多搅拌一会儿，揉面多揉一会儿，因为在揉的过程中还是有机会接触氧气的。所以第一次饧面大概15到20分钟就够了，或者看到面团开始膨胀了，就可以开始做型了。一旦酵母转入无氧呼吸阶段，菌的状态会下降，而此时二氧化碳大量产生，这个时候如果还没有做型，就会错过膨胀的黄金窗口。第二次饧面就不急了，可以等个1小时，膨胀成2倍大。概括来说，酵母发面要温水多揉一会儿，第一次饧面时间要控制；这跟泡打粉正好相反，泡打粉或小苏打要低温快揉，防止二氧化碳过早释放。做完形并二次发酵后，不能再去捏它，直接弄熟后再冷冻。不过面粉搅拌时间长，酵母好的话，第一次也可以发酵久一些。基本上都是第一次发酵完，压扁，卷起，这样在二次发酵时，里里外外好几层都含有酵母发酵层。这样做可能既能松软，又能撑起骨架。

原来和面前期是搅拌，而不是直接揉，搅拌的时候面粉变成雪花片状，把水分裹在粉内，外表面就不容易粘。然后揉的时候，里面的水分自然会揉出来，正好是面团需要的含水量。

女儿跟她老师说新年的愿望是让妈妈把爸爸带回来，没想到这已经成为三代人的愿望了……

人生主要的困惑来自对商机的不敏感；更大的困惑来自于感觉到了商机却无法将其实现。当然，副业的开拓肯定还是从自己的兴趣着手，也就是得“懂行”。我觉得衡量“懂行”的标准是经验值，更具体的，看你能否将你所从事的行业说得头头是道、看你整理了多少资料，如果你的经验能出几本书，或者现在来说更简单了，看你是否能开个持久的公众号，如果可以，那么就是入行懂行了。所以，可以试着去研究自己的某个兴趣，并撰写成文字，总有一天，它们会变成财富。研究的方法跟做功课一样，就是摘抄、整理、实践，最后提炼出自己的见解。

糖是毒品。另外，我觉得带小孩、温柔乡等也是跟打游戏一样的精神毒品。如果你沉迷、上瘾、不可自拔、影响自己的发展，都算是毒品。

前几年的今晚，都会写一写一年发生的事，起名都是《写于年末》，成就也好、经验也罢，聊以自慰。今年就算了，因为已经写了很多，而且事情只能说未完待续，等明年今天，一定会写出华美的篇章！