---
layout: post
title:  浸入文献
date:   2017-12-10 9:20:00
img: 
description: 完成了一些基本工具的学习，要形成解决实际问题的思路，还是需要浸泡到文献中去。
---

吐司涨价后，计算了一下，吃2.3片可以抵过米价，经测试，3小时没事，所以上午办公3小时后回家吃中饭。

经过几次，发现公交真的少了一班，超市开门前的那班。乘坐晚一班的则抢不到奶粉；早一班的则无法在1小时内赶回来，增加成本。只能早起走去了吗？其实可以走到一半再上车。

终于可以让停不下来的脑子塞满真正有意义的事情，不再是空洞的不能当饭吃的生活琐事和社会学伦理学了。发现网上虽然有很多关于CS229的笔记，但真正适合自己用的还是没有，需要多方整合，才能启迪不同角度的认知疏漏。于是把自己的也整理发布一下。

读书感觉对不对，就看眼睛扫下来脑子里是空空如也，还是有那么一两点引起了刺激。

有时候太聪明不是好事，一碰就了解，很容易失去深究的兴趣，如何解决这个问题？自己思考兴趣点。这样看来，教材写得晦涩也是有好处的。不过有时候这“没兴趣”，感觉更像是急于了解后面的“剧情”，不愿在眼前的耽搁。那么就照兴趣走，有问题了再回来，那时候肯定有兴趣。

见过太阳雨，但没见过那么大的，很大的太阳，很大的雨，很大的风。不知道气象台该如何描述。

居然用写blog的方式整理思路来学习，还涂涂改改了一天。还有这种操作？

发现英语数数都还不行，不能下意识地反应出来，数多了，或者倒着数，跟数阿拉伯数字完全是不同的熟练级别。可想而知其他词汇更加如此。而且英语数字听力肯定没问题，所以能听跟能说也不同。再扩展到其他学科也是一样，要靠脑子回忆的，即使懂了也是不懂。

发现ML中的很多算法在之前我自己摸索细胞分类的过程中都试过，只是当时不知道具体怎么用数学来解决。现在终于可以整合起来了。

有历史的国家一定能强大。因为有历史，就是有榜样。

ML难学，真不是因为原理有多复杂，而是其表述方式离我们的理解基础实在是相距甚远。有时候看明白了就恍然大悟，“哦，原来说的是这个呀”。理科生真的要有很好的表述能力才行；教材真的要从读者理解的层面出发才行；知识必须从实际引入，再倒叙安插原理推导，这样就永远有个方向指引着，不会迷糊，而且要突出重点，理出纲要轮廓，就是我以前说的，对知识点做好降维。难怪网上有那么多笔记和讨论询问，至少先表达成自己能懂的语言，这样以后再次回顾的时候，不至于又跟新的一样。

事情是要做的，不能光看，所以一定要找到着手点去做。感觉做不了，就一定要去找能做的那个程度。手绝不能闲着。比如ML的课件看不进，哪怕动手抄还是印不到脑子里去，那么就灰心了么，从小到大那么多难题都啃过来了，怎么会有自己智商不胜任的事，肯定是没找到对的门路。于是看Ng提供的课外辅导材料，虽然感觉看看就懂了，但毕竟不熟，所以不能眼高手低，还是要亲手写一遍。所以说，有时候虽然动手了却还不成功，其实还是不愿动手低就。

11.17，Sam生日，吃了个很结实的巧克力蛋糕，侃了宠物。

最糟糕最受挫的感觉不是搞不懂知识点，而是捋一遍后，感觉仍然发挥不上用场。

学英语主要还是在于耳朵，眼和口只是辅助。婴儿虽然记忆力强，但学会说话前经历了大量的听力训练和对语意的猜测。而我们通过在知道语意的前提下，反倒把听力训练放到了次要的位置。想当年我从方言矫正到普通话也是通过一台录音机。这其实不是记忆力的训练，而是感受器的训练，正如学游泳骑车等。小孩学得快也不是记忆力好，他们也经常遗忘，但他们的感受器很灵敏。其实小孩不光是记忆类的学得快。所以重点应该多磨练感受器，而不是反复巩固记忆。不能被浩瀚的词汇量蒙蔽了语言学习的真谛，正如小孩是不会有太高词汇量的。就像我教人学开车，是先找块空地让他们把油门提上去，即先掌握车感，随后再去学一些更精细高级的技术。语言学习也是一样，不能像驾校那样本末倒置，拿到驾照了却还没有车感。另外，通过编曲的方式学语言还是很重要的，可以减小大脑的阻力。

学技术容易，形成思路难。

学习的螺旋式上升指的不是知识点突破的难易相间，而是兴趣和大脑的吸收时间。其实很难一步到位地学完一门课程而不遗忘，哪怕是用最细致的手段。我觉得兴趣其实就等于大脑的吸收速度。大脑无法一下子承载太多的陌生知识，从而会发出兴趣动力降低的信号。等过一阵子再回顾旧知识点，就会轻松很多，会贯通很多，也会让大脑得到有一定成就感的快乐。所以“温故而知新”，大概就是这个意思。不过当某一门学科遇到“兴趣瓶颈”时，可以学另一门。但最好不要隔太久再去温故，也不能让大脑彻底放松太久。跟肌肉锻炼一样。

当大脑无法忍受的时候，先不是暂弃，而是动手做些整理。

钻研某一门技术就像闯迷宫，总是能走出来的。但更主要的是俯瞰到出来后是什么结果，然后再决定是否值得一闯。

在审视问题的时候，不仅还要审视这个“审视”本身，而且要经常保持同步进行。

烦恼就像精神鸦片，跟手机一样，在最疲劳的时候还能消磨你的精气，并逐渐打垮自己。

“愿望”是人的原动力，是一切精神动力的来源，也是健康幸福的保障。

父辈的身体不如祖辈相同年龄时期的；我现在的状况也不如父辈30来岁的时候；小孩现在也不如我小时候，各种过敏炎症。这是一代不如一代，还是人类的进化？

小时候这么多课程，惟有画画被称作“术”————美术（当然算术之类的含义变大了）。画画造就思维结构，美术则是人性修养。做事需要美感，人生需要活泛得美丽。

占领过大大小小的山头，回头看看，很难相信自己爬过了那么多艰难的险峰。是时候把小成果整合起来发起总攻了。

R学得起，但用起来没思路。机器学习拿得起，却感觉拿不住。

其实新鲜学完的再看一遍感觉都懂，然而过一阵子再去整理，并做二次笔记，感觉就能看出格局了。第一遍的笔记大概就是当局者迷，只是第一次“审视”。当然，两遍也未必够，古人说书读百遍呢。可惜现在的知识太多了，那就采用“温故知新”的方法，找相关的新知识学习，从而来带动旧知识点的运用和掌握。

学习时做详细笔记；对笔记第一遍复习找出关键知识点；第二遍复习画出网络图，也就是给知识点定位和联锁；第三遍复习对网络图进行降维。之后可以再回顾原始笔记或其他知识点，进行查漏和串联。

性格不好，学习的时候容易痛苦，主要来自拖延、懒于迂回变通，然后又急躁，总在自恃聪明浅尝辄止和自暴自弃的两极变换。得提高自律、学习时保持活络。有些事是开头难，有些算是开了头以后难。浅尝一下觉得很简单，但在自己走神的时候，突然不按自己想象的套路走了，然后就痛苦、放弃。好像大学里就经常是这种节奏。相信自己总能取胜，也要相信取胜绝不可能靠蛮劲一冲即开。相信持久论，相信知识点总是解决一个少一个的。不骄不馁，稳步前进，多学科布置，以免陷在某一门里浪费好多天影响心情。还有不能每天一样的时间安排，如果大脑知道未来的一个时间点要做什么事，兴趣就去了一半。就像吃菜一样，重复的味道，看看就没了胃口。所以上学时课程的变化排布还是有道理的。需在过程中带着兴趣去发现美，不急不忙如同游山玩水，出现这样的节奏和心理应该才是正确的。

亦不可贪功冒进，正如好吃的不能吃到厌。乘兴而归，积累小兴趣至大兴趣，以供下回再战。积小胜成大胜。不能逼自己一直吃难吃的菜，也不能一直吃好吃的菜，穿插即可。

自己的内心就是个小孩，懂得如何适从，如何约束，也就懂了如何带小孩。自己肯定是经常原谅自己的、放纵自己的，如果找不到约束自己的办法，那么具有自己遗传性格的小孩又如何能听从呵斥的摆布。而且榜样的力量毕竟是最重要的，只有家族的榜样足够强大，才能抵制外人、世俗、明星等的“榜样”影响。历史人物榜样毕竟少了些实时性，所以能陪伴小孩学习的榜样只有父母自己。

学习离不开阅读，而最有效率的学习方式就是小时候训练过无数次的总结段落大意。无论是阅读文献、还是做英语阅读，这都是事半功倍的法宝，能带自己快速复习，将零散的知识点成块地搬到脑子里反刍。现在虽然增加了看书时动笔的频率，但对每一小段都做个小结，这才是做笔记最重要的部分。当时还记得有个教奥数的老师也是用这种思路教学，说把数学解题分成几个段落大意。有点现在编程写函数的意思。

目前总结出的适合自己的两大利器就是培植兴趣、段落小结。此外，要不断审视自己的学习方法，这也是培植兴趣的一部分，迭代更新，方法必须灵活，每时每刻都有变数，保持头脑的活络警觉。

突然对成教自考感兴趣，觉得不断地学会各种知识，才是活着最快乐的事情。

出租车也是一样开得很快。7座的不错。以后国内一个家庭人口多了，可能也会有吧，叫两三辆不环保。

12.1.年夜饭。没带证件，扫了大伙的兴。

听得出来跟复读出来完全是两码事了，似乎没有小时候的模仿能力了。也可能是小时候不知道含义，重在模仿音节。而如今能听出意思，就会不自觉地用自己组织的语言复读。这样一来，学语言就没有小时候有优势了，反而成了一个“记忆”的活儿。其实语言不是记忆，应该是熟能生巧的一种技能。那么，既然聋子英语和哑巴英语是分割开来的两码事，以后就应该加强跟读训练了。跟小时候学普通话一样。其实学普通话那会儿已经开始靠记忆了，比如念“虾”的拼音。其实，靠身体的感受器学习比靠头脑的记忆力学习会高效很多，这应该就是知行合一的本质。脑养懒，体养勤。

不能控时的本质是不能控事。

当无望的时候，想到自己还有自由，应该放开思路、放开手脚去尽情地尝试。只要是有所学到，即便尝试错了也无妨。学习中虽然找目标找方法很重要，但仍避免不了弯路。而这些弯路上学到的东西，终将逐步构成未来完善的知识体系。

近距离看到一只乌鸦，一边作呕一边叫。莫非那难听的叫声都是因为乱吃东西卡喉咙了？

学东西不必面面俱到，有些东西求索的成本太大，学后的收获又暂时不明显，直接拿来用即可。当真正用到了、或运用出问题了、或有闲有兴趣的时候再去探究也不迟。这大概就是“好读书不求甚解“”。

豆芽在冷藏放了好多天，不仅出了很多芽，还有水闷味。放水洗的时候用手搅拌，结果手有刺痛感，像是摸了山药。

肌肤老了有点打击奋斗的自信，保养顺序：洗面、补水、眼霜、乳液锁水、面霜保湿、防晒SPF30。