---
layout: post
title:  立春
date:   2018-02-04 11:34:00
img: 
description: 立春和立秋。
---

2017年少两小时，2018年多两小时。这也算年年有余吧……

人应该先养兴趣再学技能。怎么养呢？就是温水煮青蛙，或者说利用斯德哥尔摩综合征，先低难度的给自己上瘾，等到每天不做点心里就痒痒的时候，水到渠成了。

师者仅“授业”也，但小孩如何“受业”，却是父母应该替孩子指明的，这不仅包含在日常的点拨中，也涵盖了生活技巧、品德习性等等，引领孩子早日开窍。

感觉土澳迷信两件事情：一是天然的，比如都知道不能吃太甜，好像白糖是化工合成的一样，但一说是天然的，甜度再高都能接受，天然的就是个卖点；二是迷信本地制造，这点跟中国截然相反，中国市场上都要写着外地的、外国的，除了本地鸡这种少数的例外，而土澳几乎所有产品上都要标注有百分之几的成分是本土的，比如我买的蜂蜜是30%本地的，要是100%本地的就很贵。

纵使有才华，也不能坚持己见，就像拍电影，谁拍出来的片子还不是个看，比如星爷很较真会得罪些人，那是真有才华没说的。主观意识的自由才是真的自由。但是道理懂再多都不能当饭吃，还是要有些能耐的。

直觉记忆再好也会忘；重复记忆是在拼偶然的串接；整理记忆是降维、是领会、是新生。但三者必须结合：在整理的时候集中精神就能强化直觉的记忆，多次的重复整理就能快速连点成片，揪出重点、暴露难点，一网打尽。

人生，就是用少量时间的痛苦来消除大量时间的折磨。能做好这种不赔本买卖的，就叫勤劳。

脚本拿来直接套用尚有无数bug，何况模型。

不喜欢《团长》这种文艺片，尤其在追求效率与激情的今天，这种片子太拖太压抑。但它却真真地刺痛着自己的心，那就是“安逸”。有时候人光听到一个词儿，不会理解到多深的程度，只有把这个词儿放到特定的背景、特定的教训中，才发人深省，才戳痛脊梁。

寒门再难出贵子？寒门有一件独有的制胜法宝，那就是生存压力。

某些部位的肌肉好像会在某些特定条件下萎缩。比如虽然一直在练俯卧撑，却突然发现做不了两个引体向上了。

《团长》真不是一部让人想追看的片，往往琐碎又不知所云，回放、拖沓，节奏慢就是它的主旋律。它可能就想停下来慢慢地思考些什么，但不能把看的人也强迫进去。要知道观众的生活也很忙，很累！观众也是在祭旗坡上荒度着岁月的人，找不到个收复南天门的办法，没能耐、又怕死，却一直怀揣着这份念想……

努力后看到的可能不是希望，而往往是更多的绝望，但要相信希望在接近。其实总以为希望在很远的地方，看得太远反而看到了绝望，其实希望并不远，就在脚下走过的每一寸地，笔下耕耘的每一个字。

引体向上不仅练背肌，也能治肩周炎。

人脑进入一种状态肯定是需要能量的，可能发生了思维电路的重排。然而一旦进入了这种状态，就会舒服很多，甚至无法自拔。小孩子脑子灵活，切换注意力很容易，进出一种状态都比较瞬间，可能相当于一个很轻量的电脑系统，而大人的系统重启可能就迟钝些。其实不光是大脑，身体也是（我越来越觉得大脑与身体有着很多相通的哲学原理）。比如长跑的时候一旦停下来会觉得很累，走一阵子走轻松了再开始跑，那段过程最累，挺过去后便又舒服起来，似乎潜力被挖了出来。所以人有两难，开头难、切换难。挺过这短时间的两难，克服自己情感上的厌恶，必能收获至宝。

很多大事也不过是琐事，如果我能坚持每天叠被子、及时洗衣服、叠衣服、洗碗；每天按时喝水泡茶、吃饭、排便、运动、睡觉、保养肌肤，每周能定时清理房间、办公用品、备份文档；每天把储备的零食吃掉一些以不至于过期、然后又定时补充以防止挨饿等等。那么我也必能每天诵读一篇诗文、听一段英文、做一点小小的研究等等。每天的坚持可以让生活不紧不慢却又倍感充实，不用刻意追求速度和质量，因为熟能生巧，这些都会化于无形。慢慢地，就会成就大事，不用心急、没有绝望，就这样过好每一天。做有计划、有意义的琐事，有意思就是好好活，好好活就会很有意思。就像种着一片园子，几天不打理就会杂草丛生，天天打理自会欣欣向荣，且有朝一日形成参天巨林。这就是业精于勤荒于嬉的道理哇。

关在金钱的牢笼里，就关在空间的牢笼里、时间的牢笼里。

一定要学会浪费！根据二八定律，在乎全部，连八成都得不到！

笔记是幅画，而且是简明的画作，从来没有密密麻麻的画作，那是刷墙。

用实例学理论，则理论永固。此亦为知行合一。

其实以前读书的时候，虽然没什么偏科，但最讨厌化学和生物，结果做了那么多年的生化；后来数学里最摸不清的是概率，结果现在搞概率。我这到底是什么命？

“每天晚上想好第二天的任务。每天早上起来反思昨日之所学，想想人生之目标，动力自然就来。贵有恒，何必三更起五更眠；最无益，只怕一日曝十日寒。”摘自人民日报，与我最近的状态很像。

其实最主要的还是“思路的形成”，而不是目标的确立。目标谁都有，但如果没有形成思路，就不会成为“心事”，无从每日“反思”，没有心事的人是散漫的、无精打采的、一看书就发困的。以前总觉得自己一看书就困、不能长期坚持是因为还没形成兴趣、没有坚强的意志和足够的目标动力、甚至怀疑是自己贫血。其实这些都是虚的，譬如定了个目标，反而容易变得好高骛远、令人绝望、最终动摇。只有在形成一定的思路以后，目标才触手可及、才有激励作用，才能形成真正的兴趣，才会看书不知疲倦。今天第一次上厕所不带手机，带了张笔记，是因为脑子里突然想到了点什么，急于理清这个节点，于是又拿出以前整理的思路笔记来看。所谓万事开头难，也许不光是指just do it的勇气，更重要的是思路形成期，也就是掌握一定的知识背景以后，就能在该领域驰骋了。另外从时间上来说也丝毫不浪费，统筹安排之后，其实做一件事跟做几件事是差不多的，甚至效率更高、更容易快速形成习惯。我们常说要用碎片化的时间来学习，其实这是必须的，只有形成思路后、自己有兴趣要去搞定一个问题了才有占用大块时间的必要，那是自发的行为。以后对孩子的学习时间也一样，必须把它打散。这样才不会失去活力和灵气。

在H&T样板房里参加了学联组织的迎春活动。今天室友都搬走了，一人独享一栋house。

加速血液循环从而实现健康的道理还是显而易懂的。抽一管血验验几乎就知道了人体的全部状况。毕竟人体每一个细胞都是由血液供给营养，产生的废物和死亡的细胞残体也是排到血管中。所以血液循环加速可以使富营养堆积的区域稀释，使代谢废物堆积的区域也及早疏通，避免引发病变。自从实施隔日跑三千米、一周跑十公里的锻炼模式以来，才一个多星期就感觉完全不一样了：不会因为偶尔晚睡一会儿，第二天起来就鼻炎发作；在开着空调的实验大楼待久了也不会感到皮肤冰凉并流鼻涕，也就是说以后我再也不用在背包里备件外套了；当然最可喜的还是看文献再也不会犯困了，可以时刻保持清醒的头脑，整天都很精神。这说明长跑的效果是可以持续存在几天的，平时的血液质量也好了很多，明显感觉到它可以给皮肤或其它边远组织提供更多热量、可以给大脑更多氧气，充沛的血液使眼睛也有神许多，感觉明亮。

做腹肌撕裂者的第一次，就似乎看到了两块腹肌，等到了第三次，看到四块了。这可能是之前仰卧起坐的基础，主要练的都是上部的腹肌。

忠于原文的翻译文字是不利于今后快速复习回顾的。所以还是要意译，相当于边翻译边整理了。可以保留暂时看不懂的语句、以及新的概念词汇。回顾时也可以精简上一次因未看明白而做的冗长翻译。

立春节气到了，这里算是立秋吧，难怪这几天一直下雨，温度骤降10度，算得上寒潮了。不知不觉夏天就算过去了？真是个四季如春的地方。