---
title: "Linux及Shell：第二章 Linux用户管理"
author: "heicai"
date: "2018年4月28日"
output: html_document
---

笔记来源：Linux系统命令及Shell脚本实践指南. 2013.11版（2015.2重印）. 作者：王军. ISBN 978-7-111-44503-6  

<!--
rmarkdown::render('C:/XinNote/Computer/Linux/Linux系统命令及Shell脚本实践指南/02_User.Rmd', 'html_document', encoding = 'UTF-8')
-->  

---  

<h2 id='content'>Content</h2>  

+ [2.1 Linux用户和用户组](#anchor1)  
+ [2.2 Linux账号管理](#anchor2)  
+ [2.3 切换用户](#anchor3)  
+ [2.4 例行任务管理](#anchor4)  

<h2 id='anchor1'>[2.1 Linux用户和用户组](#content)</h2>  

Linux是多用户**分时**系统。  
`唔`-分时操作系统 (**time-sharing** system)：“分时”是指**多个用户**分享使用同一台计算机（`唔：`“分”是分享share的意思，同时、共时），**多个程序**分时共享硬件和软件资源。**分时操作系统**是指在**一台主机**上连接**多个**带有显示器和键盘的**终端**，同时允许多个用户通过主机的终端，以**交互方式**使用计算机，共享主机中的资源。（`唔-概括：`就是可以让一台主机连接很多人的操作系统。）  

### 2.1.1 UID和GID  

UID(User ID)：是**32位整数**（所以可以记录40亿个用户，唔：2^32=4.29e9，所以这32位整数是指二进制？）。系统会自动记录“用户名”和UID的对应关系（`唔：`所以平时看到的是用户名，而不是UID）。  

用户类型：根用户、系统用户、普通用户。  

+ 根用户：root用户、**超级**用户。**UID是0**。在系统运行时都能删除所有文件系统……  
+ 系统用户：非真实使用者（`唔：`像是软件名称），UID范围**1~499**。（`唔：`最多运行499个软件？）  
+ 普通用户：UID从**500**开始编号。只能在家目录、系统**临时目录**、其他授权的目录。  


查看**进程**的用户：ps aux  
```{bash}
ps aux
```
那么ps显示啥：  
```{bash}
ps
```


查看**文件**的用户和用户组：ls -l  
```{bash}
ls -l | head  -5
```
查看文件的用户和用户组（**数字**代号）：ls -ln  
```{bash}
ls -ln | head  -5
```


每个UID至少属于一个GID，也可以属于多个GID。  
查看自己的UID和所属的GID：id  
```{bash}
id
```
查看自己所属的GID：groups  
```{bash}
groups
```


查询当前在线用户：who  
```{bash}
who
```
显示用户名和登录的终端。  

`唔-小结：`32位整数记录UID。根（超级）（0）、系统（1~499）、普通（>=500）。  
`唔-命令：`ps aux（进程）; ls -ln（数字代号）; id; groups; who（谁在线）。  


### 2.1.2 /etc/passwd和/etc/shadow  

/etc/passwd文件记录了7列内容：用户名（UID的**字符串标记方式**）、密码（x）、**UID（整数）**、GID（整数）、**说明栏（现已不使用）**（`唔：`结果中显示的还是用户名）、家目录、**登录Shell（用户登录后所使用的Shell）**（`唔：`用户是/bin/bash）。  

```{bash}
head -3 /etc/passwd
```
例如：在结果的第一行`root:x:0:0:root:/root:/bin/bash`中，root是用户名、x是密码（但不放在这里）、0是UID、0是GID、root是说明栏、/root是家目录、/bin/bash是登录Shell。  

/etc/shadow文件**只有root用户可以查看**，这种密码保存方式称为**影子密码**，记录了9列内容：用户名、密码（加密后）、密码最近修改日（从**1970年1月1日**至密码修改日的天数）、几天内不可修改密码（0则随意）、几天后需更新密码（会 提前提醒）、密码失效前警告的提前天数、密码失效后的宽限天数、账号失效日期、保留字段。  
```{bash}
head -3 /etc/shadow
```
`唔：`出现了很多的系统用户。  
例如：在`root:*:17431:0:99999:7:::`中，root用户名、\*密码、17431是1970.1.1至密码修改日的天数、0天内不可修改密码、99999天后需修改密码（但这个值不会变，也就是永久）、在密码失效的7天前提醒。  

`唔-小结：`passwd记录用户名信息7列；shadow记录密码信息9列（只有root可以查看）。  

`唔-2.1总结：`UID和GID的分类（根，系统，普通）、标识（0，1-499，500-）、查看（ps aux，ls -ln，id，groups，who）、记录文件（passwd，shadow）。  


<h2 id='anchor2'>[2.2 Linux账号管理](#content)</h2>  

### 2.2.1 新增和删除用户  

1. 新增用户：useradd  
```{bash, eval=FALSE}
useradd john  
```

系统后台的运作：  

+ UID：/etc/passwd和/etc/shadow末尾追加一条**用户信息**记录，**分配**给john一个**UID**。  
+ 家目录：在/home下给john**创建家目录**/home/john。  
+ 配置：将**/etc/skel**目录下的所有文件复制到家目录/home/john。有很多隐藏文件，是默认的**配置文件**，相当于创建用户时的模板（`唔：`skeleton）。如果自己在skel下创建了别的文件，也都会复制过去。  
+ GID：新建一个**与用户名一样**的用户组。用户john默认属于用户组john。  
```{bash}
ls -la /etc/skel # 参数a：查看隐藏文件。
```
手动指定：  
```{bash, eval=FALSE}
useradd -u 555 user1 # 参数u：指定UID。创建UID为555的用户user1。  
useradd -g user1 user2 # 参数g：指定GID。创建所属Group为user1的用户user2。
useradd -d /home/mydir3 user3 # 参数d：指定家目录。指定mydir3为user3的家目录。  
```
`唔：`上面的3个命令仍然是创建新用户，而不是修改已有用户（修改是用下面的usermod命令）。另外，其实参数g指定的不是GID，而是用户组名。  

2. 修改密码：passwd  
根用户在创建用户后，在/etc/shadow中第二列显示为两个感叹号“!!”，即还不允许新用户登录。需要设置密码才行。  
```{bash, eval=FALSE}
passwd john # 根用户设置用户john的密码。
```
若密码太简单会**提醒**，但还是会接受。  
```{bash, eval=FALSE}
passwd # 普通用户修改自己的密码。
```
若密码太简单会被**拒绝**。普通用户的passwd命令后面**不能跟参数**。  

3. 修改用户：usermod  
```{bash, eval=FALSE}
cat /etc/passwd | grep john # 查看用户john的记录。
usermod -d /home/john_new -m john # 修改家目录。参数m。
```
参数m的作用：如果用户的家目录存在（`唔：`还能不存在？还是指要创建的新目录john_new已经存在？），则创建新的目录并作为其家目录。没有参数m会报错：“/home/john_new does not exist”。（`唔：`所以参数m的意思是mkdir？）  
冻结用户：  
```{bash, eval=FALSE}
usermod -L john # 参数L。
cat /etc/shadow | grep john
```
查看时发现**密码前**多了个**感叹号“!”**，该用户被锁定。  
解锁用户：  
```{bash, eval=FALSE}
usermod -U john # 参数U。
```  
usermod命令只是对/etc/shadow文件做修改而已，所以也可以自己**手动修改**此文件（`唔：`命令大多都是在修改文件）。  


4. 删除用户：userdel
```{bash, eval=FALSE}
userdel john
```
不会删除**家目录**和**邮件信息**。  
```{bash, eval=FALSE}
userdel -r john # 参数r。
```
参数r，同时删除家目录和邮件信息。  


`唔-小结：`新增用户的后台运作（追加新用户信息和密码、分配UID和GID、创建家目录、复制skel配置文件）。修改密码和家目录、冻结与解锁、删除用户及其家目录和邮件。  
`唔-命令：`useradd -ugd; passwd; usermod -dLU; userdel -r  


### 2.2.2 新增和删除用户组  

1. 增加用户组：groupadd  
```{bash, eval=FALSE}
groupadd group1 # 创建用户组group1。  
```
**/etc/group**文件记录用户组信息。  
```{bash}
head -3 /etc/group
```
第二列是密码、**第三列是GID**、第四列是组成员。（`唔：`同样也有很多系统用户组。）

2. 删除用户组：groupdel  
```{bash, eval=FALSE}
groupdel group1 # 删除用户组group1。  
```
如果含有组成员，该操作会失败。  

`唔-小结：`用户组的记录文件/etc/group。用户组的增加、删除。  
`唔-命令：`groupadd; groupdel。  

### 2.2.3 检查用户信息  

1. 查看用户：users、who、w  
```{bash}
users # 只显示用户名。  
```
```{bash}
who # 显示用户名、登录的终端、登录的时间（如果是远程，还会接主机名或IP地址）。  
```
```{bash}
w
```
`唔：`w可能是what的意思。第一行显示当前时间、**系统运行时间**、已登录用户数量、**系统负载**。  
后面的信息分8列：USER用户名、TTY登录终端、FROM远程主机名或IP地址、LOGIN\@登录时间、IDLE**闲置时间**、JCPU该终端当前**所有**运行进程消耗的**CPU时间**总量、PCPU**当前进程**（即下一列WHAT所指）所消耗的CPU时间总量、WHAT当前运行的进程。  

2. 调查用户：finger  
```{bash, eval=FALSE}
finger
````  
`唔：`此命令默认未装载。显示的结果是登录用户信息：登录名、用户名、终端、闲置时间、登录时间、Office、office Phone。  
```{bash, eval=FALSE}
finger user1 # 显示用户user1的更详细的信息，包括家目录、Shell目录、邮件信息、计划信息。  
```

`唔-2.2命令总结`：创建用户useradd -ugd; passwd; 修改用户usermod -dLU; 删除用户userdel -r; 查看用户users; who; w; 调查用户finger user1; 创建用户组groupadd; 删除用户组groupdel。  
`唔-2.2总结简化：`前缀user、group；后缀add、del、mod；查看users（点名啦）、who（谁）、w（啥）、finger。  


<h2 id='anchor3'>[2.3 切换用户](#content)</h2>  

### 2.3.1 切换成其他用户  
su：switch user的意思。  
```{bash, eval=FALSE}
su # 不加参数则默认切换到root用户。
pwd # 查看切换后的路径，没有变，还是在john下面。  
exit # 退出root切换回原用户john。
```

```{bash, eval=FALSE}
su - # 参数-：使用root的用户环境。
pwd # 此时查看的路径已经变成了root的家目录，不再是john的了。  
```  
参数“-”不但使身份变成了root，还应用了root的**用户环境**（即/etc/passwd中定义的家目录、Shell、其他个性化设置等）。  

```{bash, eval=FALSE}
su - user1 # 切换为其他用户。
```  
root用户变成其他用户**无需密码**。（`唔：`也一定要参数“-”？）  

su命令的**缺陷**是需要输入**别人的密码**，如果变成root就需要知道root的密码，这很不安全。  

### 2.3.2 用其他用户的身份执行命令：sudo  

运行sudo命令后，系统**先检查/etc/sudoers**，判断该用户是否有执行sudo的**权限**。然后输入用户**自己的密码**，即可以他人身份执行命令。  

/etc/sudoers文件可以用vi或vim等常见的编辑器来编辑，但因其重要性，也有专门的**visudo**命令来编辑，退出时会**自动检查语法**设置。  
```{bash, eval=FALSE}
visudo
```
举例：复制文件中的一行，并修改用户名为john：  
`john ALL=(ALL) ALL`  
三个ALL分别表示可以从**任何地方登录**执行**任何人**的**任何命令**。  

定义**用户组**的sudo权限：  
`%john ALL=(ALL) ALL`  
**百分号**表示**用户组**，所有属于john用户组的用户。  

如果不想每次都输入自己的密码，可以在最后一列的“任何命令”前加**NOPASSWD**（冒号分隔）：  
`john ALL=(ALL) NOPASSWD:ALL`  

在实际中限定用户可以sudo执行的命令列表，如：  
`john ALL=(ALL) NOPASSWD:/sbin/shudown, /usr/bin/reboot`  
`唔：`把命令列的ALL替换成具体命令，用**逗号**分隔。**关机**在**sbin**下，**重启**在**bin**下。  


`唔-2.3总结：`su换身份；su -换身份和环境；sudo用别人身份执行命令。%表示用户组。三个ALL分别是登录地址、其他用户名、命令（前面可加NOPASSWD）。  


<h2 id='anchor4'>[2.4 例行任务管理](#content)</h2>  

### 2.4.1 单一时刻执行一次任务：at  
```{bash, eval=FALSE}
at now + 30 minutes # 设置30分钟后自动关机。
at> /sbin/shutdown -h now # 参数：-h now。
at> <EOT> # <EOT>不是输入的，而是按Ctrl+D产生，表示输入结束。  
```

```{bash, eval=FALSE}
at 00:00 2012-11-07 # 安排在具体的时间执行任务。  
```

```{bash}
atq # 查看任务列表（唔：at queue）。
```
第一列显示任务编号。知道了任务编号以后，可以用atrm删除任务：  
```{bash, eval=FALSE}
atrm 1 # 删除1号任务
```

如要**禁止**某用户使用该功能，则将其用户名添加至**/etc/at.deny**中。  


### 2.4.2 周期性执行任务：cron  

+ 查看crond服务的状态，是否处于运行中的进程：  
```{bash, eval=FALSE}
service crond status
```
`唔：`书中标题写的是cron，但命令写的服务是crond。实践中发现不同电脑或系统中可能不同：Win10的bash是cron（未开启，而crond不存在），Linux服务器上是crond。  

+ 开启cron服务：  
```{bash, eval=FALSE}
service crond start
```

+ 设置计划任务：crontab（`唔：`这里是cron）  
```{bash, eval=FALSE}
crontab -e # 进入编辑任务的模式
```
格式：`* * * * * command`分别表示分钟（每分钟用*/1表示，后面同）、小时、日期、月份、星期（0表示周日）、执行的命令。  
例如：`* 23-3/1 * * * service httpd restart`表示从23点到3点，**每小时**重启httpd进程。  

+ 查看任务：crontab -l  
root用户可以查看其它用户的任务：`crontab -u john -l`  

+ 删除任务：crontab -r （`唔：`没参数？）

+ 如要**禁止**某用户使用该功能，则将其用户名添加至**/etc/cron.deny**中。  


### 2.4.3 /etc/crontab的管理  

系统也有自己的例行任务，**系统例行任务**的配置文件是**/etc/crontab**。  
```{bash}
cat /etc/crontab
```

五个星号后面接的是：以什么**身份**执行，执行的**方式**（这里是**run-parts**的方式，/etc/cron.hourly等都是**文件夹**，**里面有具体的任务**）。（`唔：`比如第一行的执行方式是`cd /`进入根目录，并`&&`执行`run-parts`命令。此外，五个星号的抬头中，**dom**是day of month；**dow**是day of week。）  
除了run-parts方式外，也可以用**命令模式**运行，如：`*/1 * * * * root echo "Hello"`。  

`唔-2.4总结：`单次任务：at; atq; atrm; at.deny。周期任务：service cron status/start; crontab -e/l/r/u; cron.deny；系统的crontab，run-parts。  

`唔-本章重点：`  
查看：ps; ls -ln; id; groups; who; users、w、finger。  
废立：useradd; passwd; usermod; userdel; groupadd; groupdel。  
切换：su; sudo。  
计划：at; atq; atrm; service status; crontab。  

[回目录](#content)  

--点击下方“阅读原文”查看笔记更新--  
